name = "presuposicionalismo"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# [vars]
# You can add environment variables here

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTORIZE"
index_name = "presuposicionalismo-index"
