---
title: "Las Presuposiciones son la Clave"
pubDate: "2020-10-27"
description: "Este artículo enfatiza la importancia de las presuposiciones en la apologética cristiana, argumentando que todos los argumentos y creencias se basan en suposiciones básicas que forman la cosmovisión de una persona. Explica cómo las presuposiciones cristianas, basadas en la revelación de Dios, proporcionan un fundamento sólido para el conocimiento y la verdad."
#heroImage: "/default.jpg"
heroImage: "/src/assets/coverblog/cambiar.webp"
tags:
  - "apologetica"
  - "filosofia"
---

El enfoque de Van Til sobre la apologética se conoce popularmente como "presuposicionalismo". Van Til se dio cuenta de que cuando el creyente se encuentra con objeciones intelectuales o desafíos a su fe cristiana por parte de los incrédulos, la disputa entre ellos casi siempre es generada por, y será controlada por, sus diferentes supuestos fundamentales: sus presuposiciones[\[i\]](#_edn1). Las convicciones básicas que las personas tienen determinan cómo vivirán y cómo usarán sus mentes.

Las presuposiciones tienen un impacto en el pensamiento de los creyentes y no creyentes por igual, a menudo en formas que son relevantes y cruciales para la apologética. Consideremos el tema de la evolución. Hoy en día no faltan profesores y libros que nos digan que la investigación científica sugiere con fuerza que la especie humana desciende de formas de vida relacionadas por mutación y adaptación al medio ambiente. Tal idea plantea dificultades tanto para los creyentes como para los no creyentes, y la forma en que manejan esas dificultades es un indicador de sus diferentes presuposiciones. Algunos creyentes toman los pronunciamientos de la ciencia como motivo para modificar su compromiso con la inerrancia o la inspiración de la Biblia, otros cambian su hermenéutica para permitir una interpretación evolutiva del libro del Génesis, y otros desafían las investigaciones y los razonamientos que conducen a conclusiones evolutivas. ¿Cuál es la respuesta adecuada? Eso depende de sus presuposiciones. La evolución también plantea dificultades para el mundo de los estudiosos incrédulos. Presumiblemente, si adoptas el principio evolutivo, deberías buscar un relato evolutivo del comportamiento del hombre y las relaciones sociales - la noción de "sociobiología". Sin embargo, casi todas las investigaciones y reflexiones sociobiológicas han interpretado al hombre (como a cualquier otro animal) como egoísta, violento y anti-igualitario para perpetuar su especie o su propia descendencia. Tal punto de vista es embarazoso para la erudición liberal, especialmente sus puntos de vista tradicionales sobre la naturaleza humana y los programas sociopolíticos. Algunos denuncian así la sociobiología ("¡mera pseudociencia!"), otros rechazan la evolución por ser contraria a los ideales políticos propiamente dichos, y otros concluyen que el liberalismo debe dejarse de lado por ser contrario a la naturaleza (a la "realidad"). ¿Cuál es la respuesta correcta para un incrédulo? Todo depende de sus presuposiciones.

Un apologista no debe ignorar el hecho de que creyentes e incrédulos trabajan (externamente de todas maneras) con conjuntos de presuposiciones que son contrarias entre sí. La noción de que su discusión entre ellos podría ser perseguida de manera "neutral" es ingenua y completamente engañosa. El compromiso del cristiano con Cristo como su Señor le lleva a ver todo a la luz de quién es Cristo y lo que Cristo ha revelado en su palabra; sus razonamientos y evaluaciones están sujetos a la autoridad de Dios, hablando infaliblemente en las Escrituras. El compromiso del no cristiano consigo mismo como su propia autoridad autónoma le lleva, por el contrario, a rechazar la luz de Cristo y a ver todo según sus propias pautas de interpretación, observación, reflexión o experiencia; sus razonamientos y evaluaciones están sujetos a su propia autoridad intelectual.[\[ii\]](#_edn2) Por consiguiente, los creyentes y los no creyentes no siempre están de acuerdo sobre cuáles son los "hechos", ya sean históricos o actuales. E incluso cuando sí están de acuerdo, sus respectivas evaluaciones del significado o interpretación de esos hechos están en desacuerdo entre sí.

El cristiano lee en la palabra de Dios, y por lo tanto cree, que Jesucristo ascendió al cielo; el no cristiano dice que esta afirmación en un libro meramente humano no es creíble precisamente porque tales cosas no tienen -o no pueden tener- lugar. Debería ser obvio que están trabajando con diferentes suposiciones - sobre la naturaleza de la Biblia, sobre la naturaleza y el funcionamiento del mundo exterior, etc. El cristiano reza a Dios y su amigo es "milagrosamente" curado de cáncer, pero el incrédulo puede burlarse y decir, más bien, que no hay Dios con quien hablar y que, si se le da más información, los médicos podrían explicar cómo el cáncer desapareció repentinamente. ¿Por qué no están de acuerdo? Claramente, viven con diferentes directrices y piensan en términos de diferentes creencias subyacentes, sobre la existencia de Dios, sobre cómo deben ocurrir las cosas en el mundo natural, etc. Debido a sus diferentes suposiciones, incluso los "hechos" en los que creyentes e incrédulos están de acuerdo (de manera vaga o formal) se interpretarán de maneras muy diferentes. Pueden estar de acuerdo en el hecho de que el no creyente siente una sensación de libertad estimulante en su ateísmo, pero el creyente interpreta eso como lo que esperaríamos de un hombre que quiere racionalizar su estilo de vida licencioso y eludir el miedo al juicio. Pueden estar de acuerdo en el hecho de que el creyente siente una importante necesidad psicológica de comodidad y cuidado que se satisface con su creencia en Dios; el incrédulo interpreta eso como debilidad emocional, mientras que el creyente dice que las Escrituras enseñan que Dios nos hizo sentir esta necesidad de Él. ¿Qué hay de algo que parece menos subjetivo, como los hechos históricos, como los pasajes bíblicos que describen con precisión los acontecimientos históricos de antemano? El creyente ve esto como una evidencia de la profecía predictiva, pero el incrédulo está seguro de que la "profecía" debe haber sido escrita después del acontecimiento.

No es difícil entender, entonces, que las suposiciones que cada parte aporta a un desacuerdo religioso (o cualquier otro fundamental) definirán su diferencia de opinión y determinarán cómo cada una responde a los argumentos de la otra. Un enfoque inteligente de la apologética no puede pasar por alto esta característica del debate entre cristianos y no cristianos. También debemos reconocer que hay diferentes niveles de supuestos dentro de la perspectiva conceptual de cada persona. Cuando Sam mira el reloj y se apresura a llenar la bandeja del congelador con agua para que haya cubitos de hielo para la fiesta de esta noche, asume un gran número de cosas: que el congelador funciona, que los cubitos de hielo están hechos de agua, etc. Pero hay otras suposiciones más básicas que éstas. Por ejemplo, asume que el mundo exhibe regularidad y previsibilidad, y que la causalidad permanecerá como en el pasado (el agua en una bandeja de cubitos de hielo, cuando se coloca en el congelador, se convertirá en cubitos de hielo). Pero podemos presionar más y encontrar supuestos aún más profundos que estos en la perspectiva de Sam. Por ejemplo, cuanto más tiempo espera, menos tiempo tiene para dejar que el agua se congele; es decir, no cree que el tiempo o la oportunidad de congelar el agua aumente si se abstiene de actuar (es decir, el tiempo no "retrocede"). En este sentido, Sam supone que hay una diferencia entre él mismo (y sus pensamientos sobre la necesidad de los cubitos de hielo) y los propios cubitos de hielo.[\[iii\]](#_edn3) Ahora bien, esta ilustración nos permite ver muy claramente que ciertas suposiciones son sostenidas más tenazmente que otras por Sam. Cuando va al congelador esta noche y no encuentra cubitos de hielo, su reacción más probable es cuestionar si el congelador estaba realmente funcionando después de todo. Es mucho menos probable que repudie su creencia de que la regularidad caracteriza esta área de su experiencia ("evidentemente, el reino de los cubos de hielo es sólo un gran misterio que nadie puede explicar o predecir"). Es aún menos probable que Sam se culpe a sí mismo de la ausencia de cubitos de hielo, ya sea por apurarse a poner las bandejas en el congelador ("si hubiera esperado más tiempo, el agua habría tenido más tiempo para congelarse"), o por no pensar correctamente ("mis pensamientos son cubitos de hielo, por lo que mi mente tiene la culpa de que no podamos tomar bebidas frías").

Así que todas las suposiciones pueden afectar al razonamiento y las conclusiones de una persona, pero todas las suposiciones no tienen la misma fuerza o influencia. Se sostienen con diversos niveles de tenacidad; ocupan diferentes lugares dentro del esquema conceptual de una persona (más o menos central, más o menos periférico); controlan otras creencias en diferente medida. La apologética presuposicional presta atención, no sólo a la influencia de cualquier supuesto en el pensamiento de una persona, sino más especialmente a sus supuestos filosóficos más fundamentales o básicos. Estas creencias más profundas controlan la forma en que una persona razona y cómo interpreta y evalúa las experiencias y las pruebas. Estas creencias o suposiciones más profundas son lo que Van Til usualmente llamaba " presuposiciones". Determinan cómo una persona ve su experiencia (como las gafas de color que afectan nuestra visión). Proveen una orientación general y son tomadas como una guía confiable para el razonamiento de una persona - un "punto de referencia". Todo está organizado e interrelacionado en el sistema de pensamiento de uno por sus presuposiciones. Ejercen un control omnipresente y sistemático sobre la interpretación de la experiencia de uno, y gobiernan la forma en que uno vive su vida.

Es debido a las presuposiciones particulares de una persona (incluso cuando no las identifica conscientemente) que tiene el tipo de visión del mundo que tiene, en términos de la cual entiende todo, desde sus experiencias momentáneas hasta el significado general de la vida. Estas presuposiciones, como cualquier otra creencia, no son convicciones aisladas y autónomas que no están conectadas con otras presuposiciones. No llegamos a ellas una por una o las entendemos aparte de la forma en que se integran con otras creencias fundamentales. Están coordinadas entre sí para ser coherentes y apoyarse mutuamente. Es por eso que una visión del mundo es pensada como una red de presuposiciones - creencias fundamentales y sistemáticamente influyentes sobre la metafísica, la epistemología y la ética. Dado que las presuposiciones de una persona determinan su concepción de la ciencia, la racionalidad, la evidencia, etc., no se suele recurrir a procedimientos científicos, al razonamiento abstracto o a la verificación experiencial para "probar" las propias presuposiciones; la noción de prueba en sí misma toma su significado de esas presuposiciones. Van Til señaló:

El método reformado de la apologética... "presupondría" a Dios. ... Antes de intentar probar que el cristianismo está de acuerdo con la razón y de acuerdo con los hechos, se preguntaría qué se entiende por "razón" y qué se entiende por "hechos". Argumentaría que a menos que la razón y los hechos se interpreten en términos de Dios, son ininteligibles. ... La razón y los hechos no pueden ser llevados a una fructífera unión entre sí, excepto bajo la presuposición de la existencia de Dios y su control sobre el universo.[\[iv\]](#_edn4)

Ahora, no todos los apologistas usan la palabra "presuposición" de la misma manera que Van Til.[\[v\]](#_edn5) Carnell y Schaeffer hablaron de la "presuposición" cristiana como si fuera una hipótesis sujeta a verificación por consideraciones y razones independientes (lógica, evidencia histórica, satisfacción personal, etc.), por lo que obviamente no son los supuestos epistemológicos, metafísicos o éticos más básicos con los que una persona está comprometida. Gordon Clark, por otra parte, utilizó la palabra para designar los "axiomas" del sistema de pensamiento de una persona, que no son demostrables porque se plantean dogmáticamente como un primer principio para el que no hay nada más básico con el que demostrarlo. Naturalmente, esa concepción llevó a Clark a una postura fideísta que impide al apologista ofrecer al incrédulo motivos racionales para creer en la presuposición del cristiano.[\[vi\]](#_edn6) Van Til difirió tanto con Carnell como con Clark en el uso de la palabra "presuposición". En su opinión, una presuposición es más básica que una hipótesis, y sin embargo la red de presuposiciones que forman la visión del mundo de una persona no está más allá de la prueba racional.  Dado que las presuposiciones son las convicciones más fundamentales y coordinadas que tiene una persona respecto de la realidad, el conocimiento y la conducta, son los elementos trascendentales por los que (se espera) la experiencia de una persona puede hacerse coherente, significativa e inteligible. En consecuencia, Van Til podría escribir: "Un argumento verdaderamente trascendental toma cualquier hecho de la experiencia que desea investigar, e intenta determinar cuáles deben ser las presuposiciones de tal hecho, para convertirlo en lo que es".[\[vii\]](#_edn7) Las presuposiciones que el creyente (por un lado) y el incrédulo (por otro lado) propusieron o utilizaron fueron consideradas por Van Til como su "punto de referencia" para interpretar cualquier experiencia y guiar todo razonamiento. Se pretende que sean condiciones previas para dar sentido a cualquier pensamiento o experiencia. Como escribió Van Til, deben ser entendidas como "las condiciones que hacen inteligible la experiencia".[\[viii\]](#_edn8)

LAS PRESUPOSICIONES COMO PUNTO BÁSICO DE REFERENCIA[\[ix\]](#_edn9)

La teología católica romana concuerda con el argumento esencial de aquellos que buscan ganar para la fe cristiana en que la conciencia del hombre de sí mismo y de los objetos del mundo es inteligible sin referencia a Dios.

Pero aquí precisamente se encuentra el punto fundamental de diferencia entre el romanismo y el protestantismo. Según el principio del protestantismo, la conciencia del hombre de sí mismo y de los objetos presupone para su inteligibilidad la autoconciencia de Dios. Al afirmar esto no estamos pensando en la prioridad psicológica y temporal. Pensamos sólo en la cuestión de cuál es el punto de referencia final en la interpretación. El principio protestante encuentra esto en la trinidad ontológica autocontenida. Por su consejo, el Dios trino controla todo lo que sucede. Si entonces la conciencia humana debe, en la naturaleza del caso, ser siempre el punto de partida próximo, sigue siendo cierto que Dios es siempre el más básico y por lo tanto el punto de referencia último o final en la interpretación humana.

Esta es, en último análisis, la cuestión de cuáles son las presuposiciones últimas de uno. Cuando el hombre se convirtió en un pecador hizo de sí mismo en lugar de Dios el punto de referencia último o final. Y es precisamente esa presuposición, que controla sin excepción todas las formas de filosofía no cristiana, la que debe ser cuestionada. Si esta presuposición se deja sin cuestionar en cualquier campo, todos los hechos y argumentos presentados al incrédulo serán interpretados por él de acuerdo a su esquema. El pecador tiene gafas de color pegadas[\[x\]](#_edn10) a sus ojos que no puede quitarse. Y todo es amarillo para el ojo ictérico. No puede haber un razonamiento inteligible a menos que los que razonan juntos entiendan lo que quieren decir con sus palabras.

Al no desafiar esta presuposición básica con respecto a sí mismo como punto de referencia final en la predicación el hombre natural puede aceptar las "pruebas teístas" como totalmente válidas. Puede construir tales pruebas. Él ha construido tales pruebas. Pero el dios cuya existencia se prueba a sí mismo de esta manera es siempre un dios que es diferente del Dios de la autocontenida trinidad ontológica de la Escritura. El apologeta católico romano no quiere probar la existencia de este tipo de Dios. Quiere probar la existencia de un dios que dejará intacta la autonomía del hombre por lo menos hasta cierto punto.

EL CRISTIANISMO NO ES UNA HIPÓTESIS ENTRE MUCHAS OTRAS[\[xi\]](#_edn11)

A menudo se afirma que debemos presentar al cristianismo como una hipótesis que los hombres deben probar en la interpretación de los hechos de la experiencia. Una forma de este argumento aparece cuando los predicadores apelan a los hombres para que tomen a Cristo porque él los satisfará mejor. Ahora bien, está demás decir que, un borracho no puede estar inclinado a aceptar a Cristo de esta manera, si se entiende claramente que el borracho es en sí mismo, como lo es, el juez de lo que realmente le satisface. Pero es exactamente esto lo que el predicador no quiere. Quiere que el borracho permita que Jesús le diga lo que le satisface, y si lo hace, entonces Jesús le satisfará.

De manera similar, ciertamente podemos presentar al cristianismo como una hipótesis, lo hacemos mientras razonamos con nuestros oponentes de una manera ad hominem, es decir, si le permitimos probar lo que él puede hacer del cristianismo como una hipótesis entre muchas mediante el proceso de razonamiento unívoco.[\[xii\]](#_edn12) Pronto descubrirá que si va a aceptar al cristianismo debe renunciar a la idea de tratarlo como una hipótesis y pedir perdón por haberlo hecho.

Por otra parte, si continúa considerando al cristianismo como una hipótesis entre muchas, es una conclusión previsible que no aceptará esta hipótesis en lugar de otra. Y si aceptara al cristianismo como la hipótesis más probable, no estaría aceptando al cristianismo, sino un sustituto del mismo. Razonar sobre cualquier cosa como una hipótesis para la explicación de cualquier hecho o hechos, significa que pueden existir otras hipótesis que eventualmente deberían resultar ser verdaderas. Y si es concebible que una interpretación distinta a la de Dios debería finalmente ser dada para los hechos del universo, entonces también es cierto que estos hechos son ahora considerados como separados de Dios. Entonces nuestra conclusión debe ser que si presentamos al teísmo cristiano como una hipótesis, siempre debe ser hecho por nosotros como parte de nuestro proceso de razonamiento analógico, incluso si es en ese punto donde estamos razonando por el bien del argumento.[\[xiii\]](#_edn13)

### Por: Greg L. Bahnsen

Extracto de su libro: La Apologética de Van Til

#### _Notas:_

[\[i\]](#_ednref1) Las diferencias presuposicionales no se mencionan en cada discusión apologética. Puede que la conversación no llegue tan lejos (por ejemplo, la pausa para el café ha terminado, o la conversación sólo ha comenzado para aclarar y examinar las diferencias de opinión), u otras preguntas pueden requerir atención (por ejemplo, qué se entiende por milagro, qué versión de la Biblia utiliza el creyente, o por qué hay diferentes denominaciones). Si se prosigue con claridad de análisis, incluso estas conversaciones terminarán por abordar la diferencia en las normas definitivas de interpretación y justificación de las creencias, es decir, las diferencias en las presuposiciones. Además, en raros casos la "dificultad intelectual" que ha impedido a un incrédulo confesar lo que la Biblia declara sobre Cristo es una cuestión de hecho bastante periférica (por ejemplo, cómo encajan los relatos de la resurrección en los Evangelios) o de malentendido personal (por ejemplo, si los cristianos tienen que creer que el agua bendita puede efectuar exorcismos).

[\[ii\]](#_ednref2) Esto puede ser todo un montaje, y suele significar seguir a ciegas a profesores de la universidad u otros "expertos" que dicen lo que le gustaría oír. El apologista debe seguir desafiando al hombre que quiere ser autónomo para que piense por sí mismo. Si no lo hace, no debería salirse con la suya y presentar el debate religioso como un conflicto entre los que viven de la fe y los que se guían por la razón; se trata más bien de la confianza elegida por el incrédulo en sus expertos, frente a la confianza del creyente en Cristo y en Su Palabra. Aún así, el apologista no debe dejar las cosas en un punto muerto subjetivo. Como cristianos, afirmamos que nuestra fe es racional y objetiva, y no simplemente preferencial y subjetiva (como afirma el no cristiano).

[\[iii\]](#_ednref3) El último par de ilustraciones puede parecer a la gente más "práctica" como las reflexiones abstractas y ridículas de las que sólo los filósofos se preocupan. Esto se debe a que en nuestros asuntos cotidianos, tales supuestos fundamentales no son normalmente cuestionados, y (desde una perspectiva) no tienen por qué serlo. Pero estas creencias son asumidas genuinamente, e ilustran la diferencia entre los niveles de suposición o los diferentes grados de autoridad que nos otorgan las diferentes creencias.

[\[iv\]](#_ednref4) A Christian Theory of Knowledge (Philadelphia: Presbyterian and Reformed, 1969) ,18.

[\[v\]](#_ednref5) No hay nada de malo en ello; Van Til no tenía ningún derecho de autor sobre la palabra o la autoridad para estipular cómo debe ser usada. La palabra "presuposición" se usa de varias maneras en el inglés contemporáneo, y ni siquiera Van Til siempre la usó de la manera particular que se discute aquí. Sin embargo, si no distinguimos entre los diversos usos de la palabra por parte de los diferentes apologistas, sólo nos confundiremos cuando la utilicen.

[\[vi\]](#_ednref6) Clark apoyó la discusión racional con el no creyente y la crítica de la teoría del conocimiento del no creyente, la postura ética, etc. Pero la única "razón" (causa) por la que un incrédulo elige la Biblia en lugar del Corán es la obra regeneradora del Espíritu Santo (Tres Tipos de Filosofía Religiosa \[Nutley, N.J.: Craig Press, 1973\], 121- 23).

[\[vii\]](#_ednref7) A Survey of Christian Epistemology, In Defense of the Faith, vol. 2 (Philadelphia: Presbyterian and Reformed, 1969), 10; cf. p. 201.

[\[viii\]](#_ednref8) Christian Theory of Knowledge, 286.

[\[ix\]](#_ednref9) Un extracto de The Defense of the Faith (Philadelphia: Presbyterian and Reformed, 1955), 94-95, tomado del programa Apologetics (reimpresión, Nutley, N.J.: Presbyterian and Reformed, 1976), 45. Se añade un énfasis para destacar lo que Van Til solía querer decir con las " presuposiciones" de alguien.

[\[x\]](#_ednref10) Cabe señalar que cuando Van Til utilizó la metáfora de los " gafas de color" para las presuposiciones del incrédulo, hizo hincapié en que éstas son adoptadas voluntariamente por el pecador para que pueda ver el mundo de manera diferente, como él desea hacerlo. Pero Van Til no enseñó que todas las presuposiciones son una cuestión de elección voluntaria, o que cualquier conjunto de gafas (presuposiciones) distorsiona la realidad. Sostuvo que todos los hombres conocen a Dios por su inevitable y clara revelación, y que este conocimiento les da las presuposiciones por las cuales ver el mundo de Dios correctamente. Sin embargo, se han puesto gafas de colores en su lugar.

[\[xi\]](#_ednref11) Un extracto de Survey of Christian Epistemology, 208-9.

[\[xii\]](#_ednref12) El razonamiento "unívoco" no honra la distinción Creador-criatura, sino que asume que Dios y el hombre se acercan al conocimiento de la misma manera y bajo esencialmente las mismas condiciones. Se niega a "pensar los pensamientos de Dios después de Él" y afirma su autonomía intelectual.

[\[xiii\]](#_ednref13) El significado de esta última frase se hará evidente cuando en breve abordemos el asunto del método "indirecto" de Van Til para probar la fe analizando la consistencia interna de las visiones del mundo del creyente y del incrédulo y comparando su capacidad para dar sentido al mundo. Esto implicará pensar en las implicaciones de la visión del incrédulo "por el bien del argumento". Pero incluso cuando estamos discutiendo "dentro" de la visión del mundo del no creyente, seguiremos "pensando los pensamientos de Dios después de Él" (usando el razonamiento "analógico"). Es decir, seguiremos las presuposiciones cristianas mientras investigamos la naturaleza del sistema de pensamiento del no creyente.
