---
title: "Libertad Personal y Dignidad Humana"
pubDate: "2020-11-07"
description: "Discute la relación entre la libertad personal y la dignidad humana desde una perspectiva cristiana. Afirma que la verdadera libertad y dignidad se encuentran solo en Cristo, quien libera a las personas del pecado y les da un propósito y valor intrínseco como criaturas hechas a imagen de Dios, contrastando con las visiones seculares de autonomía."
#heroImage: "/default.jpg"
heroImage: "/src/assets/coverblog/2020-11-07.webp"
tags:
  - "apologetica"
---

_¿Qué es el hombre, para que Tú tengas de él memoria? y el hijo del hombre ¿para qué lo visites? ¡Le has hecho poco menor que los ángeles y lo coronaste de gloria y de honra!_

(Salmos 8:4–5)

## Preocupaciones centrales

En este capítulo resaltaremos asuntos de libertad personal y de dignidad humana. Hemos abordado ya, el problema de la libertad personal en el capítulo cuatro. Te animamos a repasar el material a este respecto. Aquí resumiremos brevemente el argumento acerca de la libertad humana, después nos centraremos en el problema de la dignidad humana.

La cosmovisión naturalista no puede explicar la libertad. Si el naturalismo es verdad, entonces los naturalistas no tienen ninguna razón para creer en el naturalismo. El naturalista dice que todo el pensamiento es tan solo la respuesta electro química de la materia gris del cerebro material y que estas respuestas están determinadas por nuestro medio ambiente. El pensamiento humano está en el mismo nivel en que las malas hierbas crecen. Si el naturalismo es verdad, entonces el defensor del enfoque naturalista solo está diciendo que afirma el naturalismo porque la naturaleza ha determinado que lo haga. El naturalismo contradice la libertad (y la dignidad). Él no tiene razón para declarar que el naturalismo sea verdad, simplemente está siendo forzado a decir eso.

## La Importancia de la Cosmovisión de la Dignidad

La “dignidad humana” se ocupa de nociones de valor ético, de respeto personal y del valor inherente en la vida humana. La pregunta de la dignidad humana es de un significado práctico enorme tanto para nuestras vidas mundanas como para nuestras cosmovisiones teóricas. No sólo impacta nuestras actitudes diarias y nuestra interacción con otros sino que sirve como el fundamento mismo de los derechos humanos y de una sociedad estable.

En los niveles prácticos y sociales, los supuestos básicos acerca de la naturaleza humana llevan a la mayoría de los incrédulos a distinguir al hombre de los animales. Al hacer esto, ellos están afirmando tácitamente la dignidad de la vida humana. Ellos aún intentan hacer esto desde su punto de vista de la evolución, que coloca al hombre en un continuum con los animales, solo más arriba en la escalera. O como Aristóteles lo expresaría: más arriba en la “escala del ser.”

Una manera perspicaz de ilustrar nuestro sentido inherente de dignidad es en nuestras ceremonias de funerales. A lo largo de la historia y por todo el mundo los servicios de entierros han sido utilizados para mostrar amor, respeto y aprecio por el difunto, así como simpatía, preocupación y afecto por la familia que se queda atrás. Los servicios en sí mismos casi invariablemente se realizan bajo algún tipo de ritual que refleja el sistema de creencias prevaleciente en la cultura. Como lo muestra la historia, “los ritos funerarios son tan viejos como la raza humana. En la cueva de Shanidar en Iraq, los esqueletos de los Neandertales han sido descubiertos con una característica capa de polen, la cual sugiere que los Neandertales enterraban a sus muertos con ofrendas de flores.”[\[1\]](#_ftn1) Así que aún con los supuestos evolutivos, los antropólogos reconocen la idea de la dignidad humana.

Otra forma significativa en la cual vemos la afirmación de la raza humana de la dignidad es a través del establecimiento de tribunales de justicia. Nuestro sistema legal muestra nuestra comprensión interna de la dignidad humana (¡Aunque usted, no lo crea!). Nosotros subrayamos nuestro sentido de dignidad y honor al crear estructuras sociales y códigos de marcos legales diseñados para proteger y alentar la vida, la libertad, la búsqueda de la felicidad, los derechos de propiedad, reputaciones y demás. En realidad, “la ciencia de la ley . . . no es otra cosa sino varias ciencias que están preocupadas con que el hombre viva en un estado social. La sociología, ética, política, economía política, así como la historia, biología y psicología, todas tienen un interés mutuo, porque todas ellas se relacionan más o menos unas con otras y todas son necesarias para el correcto entendimiento de cada ciencia.”[\[2\]](#_ftn2) Nuestro sentido de la dignidad tiene implicaciones amplias y enormes para la cultura humana.

Ahora bien, ¿cómo impacta esto el argumento apologético? ¿Cómo debemos usar esta pieza de información para poder realizar una crítica interna de la cosmovisión del incrédulo?

## El Problema del Incrédulo con la Dignidad

Comencemos nuestra crítica presuposicional de la cosmovisión del incrédulo con una observación interesante. Recuerda que solo los humanos tienen un sentido de dignidad y que cuando nosotros investigamos el mundo animal, no vemos nada como un funeral para el difunto. Los leones, por ejemplo, se les conocen por olfatear a sus parientes muertos y después comérselos. El respeto por los muertos como es evidenciado en los funerales y las conmemoraciones es una experiencia distintiva humana que carece de cualquier correspondencia con las actividades humanas.

Como un apologista presuposicional, debes hacer la pregunta penetrante de: Si el hombre es un animal avanzado y si nuestras prácticas puedes rastrearse de nuestros ancestros animales, ¿por qué no podemos descubrir ningún comportamiento primitivo en la respuesta animal a la muerte que haya evolucionado en nuestras ceremonias más avanzadas? ¿Por qué los humanos han expresado universalmente la dignidad de la vida humana de esta forma? Los funerales no son ejemplos del hombre siendo un animal “superior” con una inteligencia avanzada, como el desarrollo de nuestro cálculo, construcción de aviones, producción de literatura escrita, composición de música y otras actividades intelectuales de este tipo. Tampoco podemos afirmar que los funerales tengan cualquier beneficio de supervivencia para las especies homo sapiens, como por puntos de vista evolutivos de los instintos animales. Más bien, los funerales señalan nuestro sentido de dignidad y reconocimiento de valores personales, que son completamente carentes en los animales.

Como siempre sucede, el no-Creyente no puede explicar la dignidad humana. Si no existe Dios a cuya imagen fuimos creados, ¿por qué tenemos un sentido de dignidad humana? ¿Por qué hemos desarrollado prácticas sociales enfatizando nuestro valor inherente? ¿Por qué hemos establecido rituales que la confirman o códigos legales que la defienden? ¿Qué explica la dignidad humana?

El mundo incrédulo actual, generalmente afirma la dignidad de toda vida humana. Nosotros decimos “generalmente” porque en los últimos tiempos y hasta nuestros días, grandes grupos han negado la dignidad universal del hombre. Los Nazis en la Segunda Guerra Mundial no afirmaron la dignidad inherente de los judíos, denigrándolos como “comedores inútiles.” La historia del racismo japonés también es bien conocida.

La justificación de la esclavitud como se practica en muchos países musulmanes hoy en día, demuestra su negación de la dignidad humana universal. Según el clérigo y líder gubernamental, Sheik Saleh Al-Fawzan: “La esclavitud es una parte del Islam . . . La esclavitud es parte de la yihad y la yihad permanecerá mientras que exista el Islam.” Este artículo continuó señalando: “Al-Fawzan es miembro del Consejo Superior de los Clérigos, del máximo órgano religioso de Arabia Saudita, un miembro del Consejo de Edictos Religiosos e Investigación, el Imam del Príncipe Mitaeb Mosque en Tiad y un profesor en la Universidad Islámica Imam Mohamed Bin Saud, el principal centro de aprendizaje wahabí en el país.” Serge Trifkovic continúa:

_Contrario al mito de que el Islam es una religión libre del prejuicio racial, la esclavitud en el mundo Musulmán ha sido, y sigue siendo, de carácter brutalmente racista. Para encontrar hoy en día racismo anti-Negros y esclavitud verdaderamente endémicos, abiertos y crudos, uno necesita ir a las dos Repúblicas Islámicas en África: Mauritania y Sudán. La gente negra ha sido esclavizada a tal escala que el término negro se ha convertido en un sinónimo de esclavo. La raza mixta, predominantemente negroide pero auto declarada “Árabe,” habitantes de la zona en transición sub-sahariana, han sido adoctrinados en el trato a sus vecinos negros puros del sur con el desdén racista. (En la actualidad, puede ser peligroso para la vida de alguien preguntarle a un musulmán sudanés o mauritano, de apariencia obscura pero de habla árabe, si es un “negro.”)_.[\[3\]](#_ftn3)

Pero casi con certeza cualquier persona con la que puedas entrar en contacto en nuestra cultura en la actualidad, tendrán alguna noción general de la dignidad humana, aun cuando la infrinja con un racismo sutil o cualquier otra actitud pecaminosa. Necesitamos insistir sobre el problema de la dignidad humana con el incrédulo. ¿Es simplemente una convención humana? Si es así, podría ser cambiada por la sociedad. Entonces, ¿sobre qué bases estables podríamos establecer nuestro sistema de leyes, que está diseñado para proteger nuestras vidas y nuestros derechos?

## Principio Descontrolado

La noción de la dignidad no puede ser controlada razonablemente por los principios del incrédulo. Muchos puntos de vista populares han declarado incluso que todas las cosas vivientes tienen dignidad. Por ejemplo, el gran humanitario, teólogo y filósofo Albert Schweitzer (1875–1965) escribió _Reverencia por la Vida_, donde declaró este mismo principio aún en el título. En su _Filosofía de la Civilización_ estableció sucintamente su punto de vista: “La filosofía verdadera debe comenzar desde el hecho más inmediato y comprensible de la conciencia: ‘Yo soy vida que quiere vivir, en medio de vida que quiere vivir.’” Su respeto por “toda” la vida guio a conclusiones absurdas. Jack Coulehan, quien anotó la biografía de Schweitzer, señaló que “Schweitzer resistió la modernización y no mantuvo su hospital tan limpio como a sus críticos les hubiera gustado, pero que esta resistencia estaba basada mayormente en su filosofía de la ‘reverencia por la vida.’ Que aparentemente le había guiado, en la medida de lo posible, a respetar incluso las vidas de los insectos y las bacterias.”[\[4\]](#_ftn4)

Mahatma Gandhi (1869–1947) estaba comprometido con Áhimsa, que todavía permanece como un principio de la religión jainista:

_Traducido literalmente Áhimsa significa estar sin daño; ser inofensivo, no sólo para uno mismo y para otros, sino para todas las formas de vida, desde los mamíferos más grandes hasta la bacteria más pequeña . . . Al seguir esta disciplina, a los monjes jainistas se les puede observar pisando y barriendo en sus templos con el máximo cuidado a fin de evitar aplastar accidentalmente insectos rastreros o usando paños de muselina sobre sus bocas en caso de que accidentalmente se tragaran una mosca.[**\[5\]**](#_ftn5)_

Los ambientalistas extremos muchas veces caen en este campo cuando establecen cosas tales como: “El respeto por toda la vida también es muy importante. Esto significa que tú respetas el Planeta Tierra. Cuidas el medio ambiente y eres benévolo con todas las cosas vivientes.”[\[6\]](#_ftn6) Pero si eso fuera verdad, entonces aún el ser vegetariano no tendría sentido, porque ¿qué sería de la dignidad de las zanahorias?[\[7\]](#_ftn7)

Los defensores de los derechos de los animales se quejan en contra de que limitamos la noción de la dignidad solo a los humanos. Ellos están pidiendo leyes que confirmen la dignidad para toda la vida animal.

_La base más común establecida por los derechos humanos internacionales es la dignidad humana. La Declaración Universal de los Derechos Humanos sienta las bases en el Artículo I, al que todos los tratados de derechos humanos subsecuentes se refieren. El Artículo I establece, “\[t\]odos los seres humanos nacen libres y con la misma dignidad y derechos. Ellos están dotados con la razón y la conciencia, y deberían actuar entre ellos con un espíritu de hermandad . . .”_

_La dignidad humana tradicionalmente ha sido definida por teóricos y filósofos, de tal forma que se deriva del conocido chauvinismo humano. Esto es lamentable por dos razones. En primer lugar, apoyarse en una definición de especies de la dignidad humana mina la fuerza de los derechos humanos, ya que es científica y filosóficamente insostenible. En segundo lugar, basar los derechos humanos en conceptos metafísicos o irracionales dificulta más desenmascarar el especismo, debido al reconocimiento subsecuente de que los derechos legales son fabricados. Con la meta de la legitimidad multicultural y científica, la ley internacional de los derechos humanos, de lo contrario, podría referirse a bases permanentes y no metafísicas. Esto requiere de la erradicación del elemento basado en las especies_.[\[8\]](#_ftn8)

Este artículo en una revista jurídica prominente se queja de que “en la mayor parte de la historia documentada, los humanos han negado los derechos legales a otros animales y el reconocimiento como personas legales, con dos justificaciones: la ‘base teológica’ y la ‘expresión secular del orgullo de las especies.’”[\[9\]](#_ftn9) Nota el golpe en contra de nuestra cosmovisión cristiana y su base para la dignidad humana. El lamenta que las consideraciones metafísicas no han permitido una correcta valuación del valor animal y pide que las leyes cubran las expectativas evolutivas a este respecto: “Hasta hace poco, la presuposición metafísica de que los humanos no son animales ha inhibido la interacción entre la psicología humana, la antropología y la sociología con la primatología y la evolución biológica—y vice versa.”[\[10\]](#_ftn10)

## Impedimentos Materialistas

En la cosmovisión materialista tan sólo somos paquetes de información genética. ¿Qué dignidad es inherente en una colección de hilos de adn? Una vez más vemos la enorme (y ¡peligrosa!) complicación surgiendo de la negación de la metafísica y del dominio del empirismo puro en la ciencia, como lo señalaremos ahora. En la reseña del libro del biogenético, Dinesh D’Souza, él observa que:

_En este punto de vista, las preferencias subjetivas de aquellos que buscan mistificar la vida humana no cuadran con las verdades acerca de la biología humana enseñada por la ciencia. Las células de los seres humanos, señala Silver, no son diferentes en su composición química de las células de los caballos y bacterias. Si existe una cosa tal como la dignidad humana, argumenta Silver, se deriva exclusivamente de la consciencia, de nuestra habilidad para percibir y aprehender nuestro medio ambiente. “La mente humana,” escribe Silver, “es mucho más que genes que la trajeron a la existencia.” De alguna manera las reacciones electroquímicas en nuestro cerebro producen conciencia y es esta conciencia, sostiene Silver, la que es la fuente de la autonomía del hombre y del poder . . . Los genes controlan completamente la actividad de todas las formas de vida_.[\[11\]](#_ftn11)

Este problema puede ser demostrado una y otra vez a través de la literatura técnica. El Profesor de Biología de la Universidad Cornell y destacado historiador de biología, William Provine escribe: “Las implicaciones de la ciencia moderna, sin embargo, son claramente inconsistentes con la mayoría de las tradiciones religiosas . . . Ninguna moral inherente o leyes éticas existen, ni hay principios absolutos rectores de la sociedad humana. El universo no cuida nada para nosotros y nosotros no tenemos un significado final en la vida.”[\[12\]](#_ftn12) Su cosmovisión atea viene claramente expresada en esta declaración. Esto impide claramente cualquier justificación a la dignidad humana.

J. D. Bernal (1901–1971), anterior Profesor de Física en la Universidad de Londres y pionero en cristalografía de rayos X, dio la siguiente definición evolutiva de la vida: “La vida es algo parcial, continuo, progresivo, multiforme e interactivo continuamente, la autorrealización de las potencialidades de los estados del electrón atómico.”[\[13\]](#_ftn13) ¿Están los estados del electrón dignificados?

En su famosa carta a William Graham el 3 de Julio, 1881, Carlos Darwin (1809–1882) escribió: “Pero, entonces, conmigo siempre surge la horrible duda de si las convicciones de la mente del hombre, que siempre ha sido desarrollada de la mente de animales inferiores, son de algún valor o no son confiables para nada. ¿Confiaría alguien en las convicciones de la mente de un mono, si es que existe alguna convicción en una mente así?”[\[14\]](#_ftn14) El renombrado psicólogo investigador, B. F. Skinner, plantea el asunto de manera intencionada: “Para el hombre \[como\] qua hombre \[hombre como ser humano\] fácilmente podemos decirle hasta nunca.”[\[15\]](#_ftn15) Tanto para la dignidad humana.

El bien conocido biólogo, William Etkin escribe eso: “No somos más que peces mejorados . . . algo así como el diseño original de una casa que ha sido remodelada.”[\[16\]](#_ftn16) El incrédulo presiona más consistentemente para una más completa autoconciencia naturalista cuando insta a la eliminación de las limitaciones éticas sobre la investigación científica. En la cosmovisión materialista, la vida no es sagrada y la ética está en contra de lo científico. Dinesh D’Souza lo explica:

_Los tecno-utópicos no están preocupados con disminuir la santidad de la vida humana porque, ellos dicen, ésta es intrínsecamente sagrada. “Esto no es un argumento ético sino uno religioso,” dice Silver. “No tiene lógica.” El biólogo David Baltimore, un Nobel de literatura, argumenta que ‘las declaraciones acerca de prácticas inaceptables moral y éticamente’ no tienen lugar en el debate biotecnológico “porque estos son terrenos subjetivos y por lo tanto, no proveen ninguna base para la discusión.” El supuesto que comparten Silver y Baltimore, es que los moralistas están hablando de valores mientras que ellos, los científicos duros, se ocupan de hechos_.[\[17\]](#_ftn17)

## La Confusión del Azar

En el último análisis, debemos hacer nuestra pregunta apologética estándar: ¿Qué significado tiene la dignidad en un Universo azaroso? En la reseña de un libro acerca de la posibilidad de vida extraterrestre (que fue escrito por el Profesor de Historia Natural, Paul Davies) encontramos un comentario revelador. El crítico Gregory Koukl escribe: Davies “tiene algunos pensamientos interesantes acerca del impacto de la idea de la evolución acerca de la noción del valor humano y la dignidad. Si tú crees que nosotros somos el resultado de procesos naturales de causa y efecto, terminas con serios problemas con el mérito, propósito, valor y dignidad. Es difícil argumentar que alguien que es un accidente del universo tiene algún tipo de destino especial.”[\[18\]](#_ftn18)

El renombrado Profesor de Paleontología de la Universidad de Harvard, Stephen Jay Gould declaró: “La existencia humana ocupó el último mili microsegundo geológico de esta historia—el último centímetro del kilómetro cósmico o el último segundo del año geológico . . . si la humanidad surgió ayer como una pequeña ramita en una rama de un árbol floreciente. Entonces la vida puede ser que no exista, en un sentido genuino, para nosotros o por nuestra causa. Quizás somos una idea tardía, un tipo de accidente cósmico, solo un adorno en el árbol de Navidad de la evolución.”[\[19\]](#_ftn19)

El evolucionista J. W. Burrow, Profesor del Pensamiento Europeo, Universidad de Oxford, escribió la introducción para una nueva edición de El Origen de las Especies: “La Naturaleza, conforme a Darwin, fue el producto de un azar ciego y una lucha ciega, y el hombre una mutación solitaria e inteligente, luchando con los animales para su sustento. Para algunos el sentido de pérdida era irrevocable, era como si un cordón umbilical hubiera sido cortado y el hombre se encontrara a sí mismo como una parte de ‘un universo frío y desapasionado.’ A diferencia de la naturaleza como la conciben los griegos, la Ilustración y la tradición cristiana racionalista, la naturaleza Darwiniana no tiene ninguna pista para la conducta humana, no tiene respuestas para los dilemas morales humanos.”[\[20\]](#_ftn20) Bertrand Russell vio al hombre como un accidente cósmico, carente de significado:

_Tal es, a grandes rasgos, pero aún más sin propósito, más carente de significado, el mundo que la Ciencia presenta para que sea nuestra creencia. En medio de un mundo así o en cualquier parte, nuestros ideales en lo sucesivo deben encontrar un hogar. Que el hombre es el producto de causas que no tenían previsión del fin que estaban logrando, que su origen, su crecimiento, sus esperanzas y sus temores, sus amores y sus creencias, no son otra cosa sino el resultado de las colocaciones accidentales de los átomos; que ningún fuego, heroísmo, ni intensidad de pensamiento y sentimiento puede preservar una vida individual más allá de la tumba; que todos los trabajos de las edades, toda la devoción, toda la inspiración, toda la claridad del genio humano están destinados a la extinción en la gran muerte del sistema solar y que todo el templo del éxito del Hombre debe ser enterrado debajo de los restos de un universo en ruinas—todas estas cosas, si no están absolutamente fuera de discusión, aun así es casi seguro, que ninguna filosofía que las rechaza puede esperar mantenerse. Solo dentro del andamio de estas verdades, solo en el firme fundamento de la desesperación implacable puede la habitación del alma de aquí en adelante ser construida de manera segura_.[\[21\]](#_ftn21)

Al ganador del Premio Nobel, el Profesor de Biología de la Universidad de Harvard, George Wald (1906–1997) le preguntaron una vez quien era desde su punto de vista Shakespeare y contestó: “Una colección al azar de moléculas que existieron hace 400 años.”[\[22\]](#_ftn22) El muy respetado antropólogo Loren Eiseley (1907–1977), quien encabezó el Departamento de Antropología de la Universidad de Pensilvania. Comentó una vez que: “El hombre no tenía que ser nada más que una mariposa o una oruga, Él simplemente emergió de un vacío infinito para el que no tenemos un nombre.”[\[23\]](#_ftn23)

Debemos recordar que el azar no puede explicar la moralidad ni los universales. Como consecuencia, no puede afirmar la dignidad humana. ¿Cuál es el significado de la dignidad en un universo azaroso? El azar destruye la posibilidad misma del significado y la relevancia, derribando juntamente la noción de la dignidad. Gregory Koukl resalta los problemas del materialismo y del azar para explicar la dignidad humana:

_¿Por qué la ciencia le roba a los seres humanos su dignidad? La Ciencia ha limitado su área de estudio al área de los acontecimientos naturales. Nos dice que esa es la única área que realmente existe. A esto se le llama naturalismo filosófico. Si solo existe la naturaleza, entonces resulta que somos meramente partes de una maquinaria en los trabajos de la naturaleza y somos las víctimas involuntarias de la maquinaria de la causa y efecto sucediendo en el tiempo sin ningún plan. Esto le roba su dignidad a los seres humanos. Claramente es, que si somos el producto del azar, entonces no tenemos propósito. Suena duro argumentar que no somos en nada diferentes a cualquier otra cosa en esta tierra que ha resultado del proceso de la evolución._

_La declaración de que somos un tipo de dignidad peculiar resulta ser un tipo de especismo. Nosotros vemos arbitrariamente nuestras especies como cualitativamente más valiosas que otras especies, pero la realidad del asunto es que en la naturaleza ese no es el caso. Davis reconoce que si nos quedamos con el naturalismo filosófico, somos robados del valor único y la dignidad, y nos convertimos en uno de muchos organismos vivos que no tienen distinción cualitativa._

_Uno podría argumentar que somos más sofisticados en nuestros logros evolutivos, pero ¿qué nos separa del resto? Nada. Ese es un juicio de valor y no existen juicios de valor como ese, que no tiene sentido en la naturaleza porque la naturaleza carece de valor. Los valores son una construcción filosófica. Estos son una noción moral y teológica y no tienen lugar, hablando estrictamente, en un mundo que está definido simplemente por la ley científica.[**\[24\]**](#_ftn24)_

La dignidad no reposa sobre nada en el Universo evolutivo. Esta desafía la ley de la gravedad, por así decirlo, y simplemente cuelga allí—si se afirma del todo. Como se ha establecido, un ateo es alguien que no tiene medios invisibles de soporte. En el mejor de los casos, la dignidad es tan solo una convención humana. Y cuando es afirmada, se vuelve una contradicción en la cosmovisión del incrédulo. Nuestro desafío Presuposicional debe señalar esta tensión dialéctica. Nancy Pearcey observa la destrucción de la libertad y la dignidad en la cosmovisión evolutiva, mencionando sus implicaciones contradictorias:

_Contradicciones propias similares son endémicas en la literatura de la psicología evolutiva. Un ejemplo principal es “El Animal Moral”, donde el autor Robert Wright dedica cientos de páginas para describir a los seres humanos como “robots,” “títeres,” “máquinas” y “relojes Suizos” programados por la selección natural. Él insiste en que la “bioquímica gobierna todo” y que el libre albedrío es pura ilusión. Él desenmascara nuestros impulsos morales más nobles como los “estratagemas de los genes” de supervivencia y los pone como simples dispositivos “que se encienden y se apagan conforme al interés propio.” Pero entonces, en un gran salto de fe, Wright insiste que nosotros ahora somos libres para escoger nuestros ideales morales y nos insta a practicar el “amor fraternal” y nuestra “empatía sin límites.”_

_Esta contradicción interna persistente proviene del hecho de que la psicología evolutiva es una investigación esencial para la moralidad secular. El Darwinismo deja al mundo moderno libre de las tradiciones religiosas y de los sistemas de significado; el resultado es una cultura a la deriva en un mar de relativismo. Ahora el Darwinismo es en sí mismo sondeado como una fuente de significado, una guía cósmica para los problemas de la vida. Con todo, el punto de vista Darwiniano de la naturaleza es tan negativo, tan contrario a las nociones tradicionales de la dignidad humana, la moralidad y la razón (sin mencionar el sentido común), que existe un impulso casi irresistible de dar un salto de fe hacia atrás, hacia aquellas nociones tradicionales, sin importar que no tengan apoyo de la teoría. Porque, ¿quién puede vivir con una teoría que nos dice que la “ética es ilusoria” y que la ‘moralidad es simplemente una adaptación puesta en marcha para promover nuestros fines reproductivos,’ en las palabras de Michael Ruse y E. O. Wilson? ¿Quién puede vivir con una teoría que nos dice que si ‘la selección natural es suficiente y verdadera, es imposible que un patrón de ‘comportamiento altruista’ o genuinamente desinteresado evolucione,” en las palabras de M. T. Ghiselin?_[\[25\]](#_ftn25)

## El Punto de Vista Cristiano

El punto de vista cristiano de la dignidad humana es afirmado en la Declaración de la Independencia de Estados Unidos, la cual declara correctamente que los hombres están “dotados por su Creador de ciertos derechos inalienables.” La Escritura en varias ocasiones establece la base firme de la dignidad humana, declarando que el hombre existe como la imagen del Dios eterno (Génesis 1:26–27; 9:6; 1 Corintios 11:7; Efesios 4:24; Colosenses 3:10; Santiago 3:9). El salmista declara que Dios hizo al hombre “un poco menor a Dios” (Salmos 8:5).

Nuestro valor está subrayado por el hecho de que el Hijo de Dios tomó sobre sí mismo la humanidad verdadera, para poder redimirnos de nuestros pecados. “Así que, por cuanto los hijos participaron de carne y sangre, Él también participó de lo mismo para destruir por medio de la muerte al que tenía el imperio de la muerte, esto es al diablo y librar a todos los que por el temor de la muerte estaban durante toda la vida sujetos a servidumbre.” (Hebreos 2:14–15; Romanos 8:3; Filipenses 2:7–8).

Nuestro Dios santo aun nos proveyó en la Escritura un sistema de moralidad y de ley que establece protecciones especiales para el hombre, afirmando su dignidad. La ley fundamental a este respecto es el Sexto Mandamiento: “No matarás” (Éxodo 20:13; Deuteronomio 5:17). Esta ley está establecida específicamente sobre la realidad subyacente de la imagen de Dios en ella: “El que derrame sangre de hombre, por el hombre su sangre será derramada; porque a imagen de Dios es hecho el hombre” (Génesis 9:6). Esta ley medular está aplicada de muchas maneras en las jurisprudencias del Antiguo Testamento y en los principios morales del Nuevo Testamento. Jesús inclusive, la aplica al odio de otro humano (Mateo 5:21–22).

La Escritura habla de un gran valor en la reputación y en el nombre, aun prefiriéndoles antes que el oro. “El buen nombre es más deseado que las grandes riquezas, el favor es mejor que la plata y el oro” (Proverbios 22:1). “Mejor es la buena fama que el buen ungüento” (Eclesiastés 7:1). También lamenta la vergüenza, que golpea la dignidad y el honor de alguien (Salmos 31:17; 69:19; Proverbios 13:18; 1 Corintios 11:22).

Robert Reilley expresa el problema del incrédulo muy bien en _La Reseña Intercolegial_: “El problema es que, al negar la posibilidad de una relación entre Dios y el hombre, el ateo también niega la posibilidad de una relación justa entre el hombre . . . La vida humana es sagrada solo si existe un Dios que la santifica. De otra manera el hombre es sólo otra colección de átomos y puede ser tratado como tal.”[\[26\]](#_ftn26) El filósofo Patrick D. Hopkins resume el punto de vista del hombre incrédulo:

_Este punto de vista representa esencialmente a los humanos como moderadamente inteligentes, moderadamente conscientes, moderadamente creativos, físicamente débiles, animales emocionales, sociales y mortales participando en un proceso continuo de evolución carente de cualquier gran propósito o diseño. Nosotros nacemos, vivimos, comemos, excretamos, pensamos, sentimos, creamos, nos emocionamos, organizamos, clasificamos, competimos, cooperamos y morimos. Aunque somos en verdad más inteligentes y probablemente más conscientes y mucho más auto conscientes que otros animales, somos esencialmente lo mismo que los animales, difiriendo solo en cierto grado y no de especie, y no difiriendo tanto como solemos pensar. No somos únicos metafísicamente, no clasificamos entre los ángeles y las bestias, no somos almas dentro de un cuerpo_.[\[27\]](#_ftn27)

En definitiva, podemos ver claramente “la imposibilidad de lo contrario.” Solo el cristianismo provee “las precondiciones para la inteligibilidad.” La cosmovisión del incrédulo destruye aun la dignidad de la vida humana, de este modo socava aun el motivo para discutir en contra del cristiano. De hecho, el incrédulo no puede ni siquiera explicar su argumento con el creyente acerca de la libertad humana, porque en su visión nosotros solo estamos sujetos a las leyes de la física.

## Observaciones exegéticas

En \[este capítulo\] hemos tenido muchas oportunidades de referirnos a Génesis 1 y la creación del hombre. El libro de Génesis es extremadamente importante para la cosmovisión cristiana ya que declara el origen del hombre y del Universo por medio del poder soberano de Dios. También habla de la esencia misma de lo que es ser un humano y poseer dignidad. Reflexionemos brevemente en la creación del hombre y en las implicaciones de su dignidad personal exaltada.

En Génesis 1 y 2 encontramos la explicación del Creador del origen del hombre. En lugar de investigar el código genético de su ascensión del lodo, deberías estar leyendo los registros de Génesis de su creación hecha por Dios. Génesis habla elocuentemente del honor y la dignidad del hombre como la creación del Dios racional contraria a su evolución por el azar irracional. Estudiemos algunos de los mensajes en Génesis que señalan la dignidad del hombre.

_El Hombre es la cúspide de la creación._ En la explicación de la creación descubrimos una narrativa fluida y bien ordenada bosquejando seis días de la actividad creadora de Dios. El comentarista del Antiguo Testamento, Derek Kínder, declara que “la marcha de los días es un proceso tan majestuoso como para no tener una implicación de secuencia ordenada; también parece demasiado sutil adoptar una visión del pasaje que descarta una de las impresiones primarias que provoca en un lector ordinario.”[\[28\]](#_ftn28) En realidad, de los Días 1 al 5 establece el medio ambiente para el hombre en el cuál vivirá. La vegetación es para su comida (Génesis 1:29); los animales son para que gobierne sobre ellos (Génesis 1:26).

El Día 6 entonces, aparece como la última etapa del desarrollo rápido del proceso creativo. El hombre forma el clímax especial de la actividad creativa de Dios. El sexto día es, por lo tanto, el gran final de la creación, estableciendo al hombre como la meta y punto más alto del trabajo de amor de Dios.

_El Hombre fue creado después del consejo inter-Trinitario._ Después de que Dios creó todo lo demás simplemente por medio de Su palabra hablada, se prepara para crear al hombre. Y lo hace con un característico consejo interTrinitario: “Hagamos al hombre a nuestra imagen” (Génesis 1:26). La expresión plural “hagamos” alude a las personas de la Trinidad y no a ángeles, en ese sentido: sólo Dios es el Creador (Génesis 1:1; Nehemías 9:6); el hombre es creado sólo a la imagen de Dios (Génesis 9:6; Santiago 3:9); Dios el Hijo (Juan 1:3; Colosenses 1:17) y Dios el Espíritu (Génesis 1:2) están asociados con Dios el Padre en la creación. Este consejo deliberativo subraya la importancia de la creación del hombre para la narrativa.

_El Hombre es creado a la imagen de Dios._ El texto claramente establece el carácter distintivo del hombre en ser la misma imagen de Dios: “Entonces Dios dijo, ‘Hagamos al hombre a Nuestra imagen, conforme a Nuestra semejanza; y señoree en los peces del mar, en las aves de los cielos, en las bestias, en toda la tierra y en todo animal que se arrastra sobre la tierra.’ Y creó Dios al hombre a su imagen, a imagen de Dios lo creó; varón y hembra los creó” (Génesis 1:26–27).

La Escritura muestra varias formas en que el hombre es la imagen de Dios. Dios habla (“entonces dijo Dios,” 1:3, 6, 9, 11, 14, etc.); el hombre habla (Génesis 3:9–10). Dios hace cosas (Génesis 1:7, 16, 31; 2:3); Adán cultiva el jardín (Génesis 2:8) y sus hijos hacen cosas (Génesis 4:20–24). Dios “nombra” los elementos de la creación (“Y llamó Dios,” Génesis 1:5, 8, 10); el hombre nombró a los animales (Génesis 2:19) y a su esposa (Génesis 2:23). Dios ejerce dominio (Génesis 1:1, 31); al hombre se le es dado dominio sobre las creaturas (Génesis 1:26, 28). Dios descansa de sus obras (Génesis 2:2); el hombre sigue el patrón de descanso (Éxodo 20:9–11). El hombre es la imagen de Dios.

_El Hombre es creado en intimidad por Dios._ En Génesis 1 Elohim (traducido como “Dios”) aparece a lo largo de la explicación de la creación. Elohim actúa como “el poderoso” quien realiza la creación de todo el universo (Génesis 1:1; 2:1, 4) sin esfuerzo tan sólo por Su palabra (ocho fíat rápidos repartidos en seis breves días). Pero en Génesis 2; en lugar de enfatizar el poder del Creador, Moisés enfatiza su relación íntima: Dios y el hombre están en un pacto. Esto es indicado cuando Moisés importa el nombre de pacto (“Jehová,” traducido como “Señor”) dentro del contexto de la creación del hombre (Génesis 2:7). Además, Dios forma amorosamente el cuerpo del hombre y sopla en él el aliento de vida (Génesis 2:7), mientras que los animales fueron una producción en masa (1:20, 24).

_El Hombre es creado para tener comunión con Dios._ En Génesis 3 encontramos el comentario casual de que Dios “estaba caminando en el jardín al aire del día” y buscando a Adán (Génesis 3:8–9). Dios conversó con el hombre cuando le informó de Su abundante provisión (Génesis 2:16), límites morales (Génesis 2:17) y cuando lo buscaba en el jardín (Génesis 3:9–11). Como el salmista efundió: “¿Qué es el hombre para que tengas de él memoria, y el hijo del hombre para que lo visites?” (Salmos 8:4). A lo largo de la Escritura vemos a Dios no sólo comunicándose con el hombre, sino preparando los medios para que el hombre se pueda acercar a Él en adoración, oración y comunión (ejem., Salmos 42:2; 96:8).

_El Hombre es creado como una persona moral._ Con la creación terminada en Génesis 1:1–2:3, leemos en Génesis 2:4. Las primeras palabras de Génesis 2:4 introduce una nueva sección que se enfoca en el hombre y su periodo de prueba en el jardín: “Estos son los orígenes de los cielos y de la tierra cuando fueron creados.” Génesis 2:4b empieza con la expresión en hebreo, “el día que” que es un modismo para “cuando.” Así es que 2:4b dice: “Cuando Jehová Dios hizo la tierra y los cielos.” El autor está asumiendo que la creación de la tierra y los cielos ha sido completada. En realidad, acaba de terminar de narrar la explicación de la creación en el capítulo 1. Así que con la creación como antecedente, empieza a establecer la historia del hombre—y su caída moral.

En lugar de sumergirse directo en la historia, empieza dando algunos antecedentes acerca de los eventos del Día 6. La primera cosa que cuenta acerca de la creación del Día 5 es que no había arbustos silvestres del desierto en la tierra ni había grano cultivado. Hay una razón para la ausencia de ambos. No había arbustos silvestres del desierto porque Dios no había enviado la lluvia y no había grano cultivado porque no había un hombre que trabajara la tierra: “Y toda planta antes que fuese en la tierra y toda hierba del campo antes que naciese; porque Jehová Dios aún no había hecho llover sobre la tierra, ni había hombre para que labrase la tierra” (Génesis 2:5).

En Génesis 2:5 Moisés no está diciendo que no había nada de vegetación durante este tiempo, sino que había una ausencia de tipos específicos de vegetación. Él nos había dicho antes que Dios creó plantas que dan semillas y árboles que dan fruto en el 4to. día (Génesis 1:11–12). Aquí nos informa que no había arbustos silvestres del desierto ni granos cultivados. Cuando la creación de Adán es narrada después de este comentario, descubrimos que no tuvo que atravesar con hacha las malas hierbas y zarzas silvestres, tampoco tuvo que romperse la espalda con una azada. Más bien, Dios creó un medio ambiente agradable, pacífico y productivo para Adán (Génesis 2:8–14). Fue hasta después que aparecieron las zarzas que los azadones se volvieron necesarios— después que Adán se reveló contra su Creador (Génesis 3:17–18). Dios le había advertido de las consecuencias mortales del fracaso moral (Génesis 2:16–17).

_El Hombre es creado para gobernar responsablemente._ En Génesis 1 observamos que los animales no son designados para “gobernar.” Solo el hombre ha de gobernar. De hecho, el hombre ha de gobernar sobre las creaturas de la tierra, el aire y el mar (Génesis 1:26, 28). Dios declara terminantemente esto. El salmista alaba a Dios por poner al hombre sobre las creaturas (Salmos 8:6–8). En ningún lugar viene que el hombre comparta este gobierno con los animales; el hombre les puso nombre a los animales (ejerciendo autoridad sobre ellos) al empezar a gobernarlos (Génesis 2:20). En realidad, una característica importante de la caída histórica de Adán, es que le estaba permitiendo a un animal (la serpiente) ejercer gobierno sobre él (Génesis 3:1–7, 14–15).

Así es que, el hombre tiene tanto un impulso básico constitucional de ejercer dominio al ser creado a la imagen de Dios, como una responsabilidad fundamental de hacerlo al habérsele sido ordenado en el Mandato de la Creación. La tarea distintiva del hombre en el mundo de Dios de acuerdo con el plan de Dios es desarrollar la cultura. Por consiguiente, aprendemos que:

_El Hombre es creado como un ser con capacidad de inventar._ Es interesante notar, que el hombre caído fue impulsado por las hazañas culturales más allá de las expectativas de los antropólogos y sociólogos humanistas. Vemos el efecto y la importancia del Mandato de la Creación muy temprano en la historia en las hazañas de fomento de la cultura de los descendientes de Adán. En la Biblia el hombre es visto actuar como una creatura orientada al dominio, sometiendo con justicia a la tierra y desarrollando una cultura como un mayordomo debajo de Dios, a pesar de la entrada del pecado. El hombre rápidamente desarrolló varios aspectos de la cultura social: la cría del ganado, la creación de la música, la elaboración de herramientas de metal y así sucesivamente (Génesis 4:20–22). Sobre su propia creación, el hombre no sólo se le ordenaba que desarrollara toda la creación de Dios, sino que en realidad comenzó a hacerlo.

En todo esto, descubrimos evidencia clara e irresistible de la dignidad del hombre. Él es la cúspide intencional de Dios de la creación. Él es creado después del consejo inter-Trinitario, es creado a la misma imagen de Dios y con el propósito de tener comunión con Él. El hombre es una persona moral distinguida llamada a gobernar en la tierra y a desarrollar la cultura para la gloria de Dios. El cristianismo afirma la dignidad del hombre y provee las precondiciones necesarias para su inteligibilidad.

**Extracto del capítulo 12 del libro: ¡Prepárate para la Buena Batalla!: La metodología Apologética de Greg L. Bahnsen.**

---

[\[1\]](#_ftnref1) El artículo en Wikipedia acerca de los funerales contempla las costumbres en la Roma Antigua, Japón, África, Escocia y los Estados Unidos. El estudio de los osarios (cofres funerarios) de los funerales son de gran interés para los arqueólogos que han encontrado incontables osarios al documentar los ritos funerarios en la antigua Persia, Babilonia, Israel y otras culturas.

[\[2\]](#_ftnref2) John Maxcy Zane, La Historia de la Ley 4, 2da. ed. (Indianápolis, IN: Liberty Fund 1998), 2.

[\[3\]](#_ftnref3) Serge Trifkovic, “Record Wretched del Islam sobre la Esclavitud,” FrontPageMagazine.Com (Noviembre 9, 2003): http://archive.frontpagemag.com/readArticle.aspx?ARTID=21060, accessed 6-3-13

[\[4\]](#_ftnref4) “Literatura, Artes y Base de Datos de Medicina”: litmed.med.nyu.edu/Annotation?action=view&a nnid=11876%EF%BF%BD%C3%9C, consultado el 6-3-13

[\[5\]](#_ftnref5) “Áhisma,” en el sitio web bbc: http://www.bbc.co.uk/religion/religions/jainism/living/ahimsa\_1. shtml, consultado el 6-3-13

[\[6\]](#_ftnref6) Red Internacional de Jóvenes del Mundo, “iq-eq-sq”: http://www.worldyouthnetwork.com/ PDF/5th.pdf, consultado el 6-3-13

[\[7\]](#_ftnref7) Un comediante dijo una vez: “Yo soy vegetariano no porque ame a los animales sino porque odio a las plantas.” Otro reflexionó: “Si Dios no quería que comiéramos animales, ¿Por qué los hizo de carne?

[\[8\]](#_ftnref8) Kyle Ash, “Derechos Internacionales de los Animales: Especismo y la Dignidad Humana Excluyente,” Revista de la Ley Animal, Universidad Estatal de Michigan, Colegio de Leyes (11) 196: http:// www.animallaw.info/journals/jo\_pdf/vol11\_p195.pdf, consultado el 5-31-13

[\[9\]](#_ftnref9) Ash, “Derechos Internacionales de los Animales: Especismo y la Dignidad Humana Excluyente,” 197

[\[10\]](#_ftnref10) Kyle Ash, “Derechos Internacionales de los Animales: Especismo y la Dignidad Humana Excluyente,” 206.

[\[11\]](#_ftnref11) Dinesh D’Souza, “Permaneciendo Humano: El Peligro de la Tecno-utopía,” National Review (Enero 22, 2001).

[\[12\]](#_ftnref12) William Provine, “Científicos, ¡Enfréntenlo! La Ciencia y la Religión son Incompatibles,” The Scientist, 5 (Septiembre 1988), 10.

[\[13\]](#_ftnref13) J. D. Bernal, El Origen de la Vida (New York: Universe Books, 1967), xv.

[\[14\]](#_ftnref14) Rousas J. Rushdoony, La Mitología de la Ciencia (Nutley, N. J.: Craig, 1967).

[\[15\]](#_ftnref15) Schaeffer, Entonces, ¿cómo deberíamos Vivir? en La Obra Completa de Francis Schaeffer: Una Cosmovisión Cristiana, 5 vols. (Westchester, IL: Crossway Books, 1985), 5:230.

[\[16\]](#_ftnref16) Bolton Davidheiser, Evolución y Fe Cristiana (Nutley, NJ: Presbyterian and Reformed, 1969), 157.

[\[17\]](#_ftnref17) Dinesh D’Souza, “Permaneciendo Humano: El Peligro de la Tecno-utopía” National Review (Enero 22, 2001).

[\[18\]](#_ftnref18) “Azar y Dignidad” (http://str.convio.net/site/News2?page=NewsArticle&id=5202, consultado el 6-3-13).

[\[19\]](#_ftnref19) Stephen Jay Gould, Vida Maravillosa (New York: W. W. Norton, 1989), 44.

[\[20\]](#_ftnref20) J. W. Burrow, introducción en J. W. Burrow, ed., Charles Darwin, El Origen de las Especies por Medio de la Selección Natural (Baltimore, MD: Penguin, 1974), 43.

[\[21\]](#_ftnref21) 4 Bertrand Russell, La Adoración de Un Hombre Libre: Misticismo y Lógica (New York: George Allen and Unwin, 1917), 46

[\[22\]](#_ftnref22) Schaeffer, Entonces, ¿cómo debemos Vivir? 5:230.

[\[23\]](#_ftnref23) Citado en Davidheiser, Evolución y Fe Cristiana, 149.

[\[24\]](#_ftnref24) _Gregory Koukl, “Azar y Dignidad”: http://str.convio.net/site/News2?page=NewsArticle&id=5202, consultado el 6-3-13_

[\[25\]](#_ftnref25) Nancy Pearcey, “Cantante en la Lluvia,” First Things 106 (Ocubre 2000), 57–63: http://www.arn. org/docs/pearcey/np_ftreviews1000.htm, consultado el 6-3-13

[\[26\]](#_ftnref26) Robert R. Reilly, “Ateísmo y Control de Armamento,” Intercollegiate Review, 24 (Fall 1988), 15.

[\[27\]](#_ftnref27)Patrick D. Hopkins, “Transcendiendo al Animal: Como es que el Transhumanismo y la Religión Son y no Son Parecidas,” Journal of Evolution Technology 14:1 (Agosto, 2005), 13–14: http://www. jetpress.org/volume14/hopkins.html, consultado el 6-3-13

[\[28\]](#_ftnref28) Derek Kidner, Génesis: Una Introducción y Comentario (Downers Grove, IL: InterVarsity, 1967), 54–55.
